
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import typecontrol.filters.IntFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marwen
 */
public class tv extends javax.swing.JFrame {
int valeur; int nb = 1;
    /**
     * Creates new form tv
     */
    public tv() {
        initComponents();
        
        jTextField1.setDocument(new IntFilter(4));
        valeur = randa();
        jLabel2.setText("");
        jTable1.removeAll();
        
        jTextField1.setText(null);
        nb =1;
    }
    
    
    public int randa(){
        int val =0;
        
        while (!(condition(val))){
        Random rd = new Random();
        val=rd.nextInt(9999)+1;}
        return val;
    }
    
    public void stop(){jButton1.setEnabled(false);
    }
    public void init(){
        valeur = randa();
        jLabel2.setText("");
        int rows = jTable1.getRowCount(); 
for(int i = rows - 1; i >=0; i--)
{
   ((DefaultTableModel)jTable1.getModel()).removeRow(i); 
}
        jTextField1.setText("");
        nb =1;
        jButton1.setEnabled(true);
    }
    
    
public boolean condition(int a){
    int a1,a2,a3,a4;
    a1=a/1000;
    a2=(a-(a1*1000))/100;
    a3=(a-(a1*1000)-(a2*100))/10;
    a4=a-(a1*1000)-(a2*100)-(a3*10);
    
    if ((a<1000)||(a1==a2)||(a1==a3)||(a1==a4)||(a2==a3)||(a2==a4)||(a3==a4)){return false;}
    else {return true;}
    
}

public int a1(int a){return a/1000;}
public int a2(int a){return (a-(a1(a)*1000))/100;}
public int a3(int a){return (a-(a1(a)*1000)-(a2(a)*100))/10;}
public int a4(int a){return a-(a1(a)*1000)-(a2(a)*100)-(a3(a)*10);}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("tenter votre chance");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tente n°", "Numero donné", "Réponse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(3);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("vérifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jLabel2.setText("");
        if(jTable1.getRowCount()>0)
        {jTable1.removeRowSelectionInterval(0, jTable1.getRowCount()-1);}
        
        
        
        int X[] = new int[4];
        X[0]= a1(valeur);
        X[1]= a2(valeur);
        X[2]= a3(valeur);
        X[3]= a4(valeur);
        if (jTextField1.getText().length()<4){jLabel2.setText("le numéro doit avoir 4 chiffres");}
        else{
        int tente = Integer.parseInt(jTextField1.getText().toString());
        
        if (tente<1000){jLabel2.setText("le nombre ne commence plus avec 0");}
        else{
        
        
        if (!(condition(tente))){jLabel2.setText("un chiffre ne doit pas se répéter");
        }
        else{
        
        int Y[] = new int[4];
        
        Y[0]= a1(tente);
        Y[1]= a2(tente);
        Y[2]= a3(tente);
        Y[3]= a4(tente);
        
        
        int t,v;
        t=0;
        v=0;
        
        for (int i=0;i<4;i++){
            for (int j=0; j<4;j++){
                
             if (X[i]==Y[j]){
                 
                 if (i==j){
                     t++;
                 }else {
                     v++;
                 }
                 
             }   
                
                
            }
        }
        
        System.out.println(valeur);
        
        boolean b = false;
        int deja =0;
        for (int i = 0; i<jTable1.getRowCount();i++){
            
            if (tente == (int) jTable1.getValueAt(i, 1)){b=true; 
            deja = i;}
        }
        
        
        if (b==true){jLabel2.setText("vous avez déjà proposé cette valeur, ne perdez pas de chance");
        jTable1.setRowSelectionInterval(deja, deja);
        }else{
        String res = String.valueOf(t)+" torreaux et "+String.valueOf(v)+" vaches";
        
        
        ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{nb,tente,res});
        
        jLabel2.setText("le résultat de " + String.valueOf(tente)+" est: " +res);
        
        nb++;
        
        if (nb>8){
        int confirm=JOptionPane.showConfirmDialog(this, "Désolé, vous avez perdu, le numéro que vous ne l'avez pas trouvé est: "+ String.valueOf(valeur)+", voulez vous rejouer?");
if(confirm==0){                
    new tv().setVisible(true);
    this.setVisible(false);
}else{stop();}
        
        }
        
        
        }
        
        if (t==4){
        int confirm=JOptionPane.showConfirmDialog(this, "BRAVO, vous avez gagné, le numéro est: "+ String.valueOf(valeur)+", voulez vous rejouer?");
if(confirm==0){new tv().setVisible(true);
    this.setVisible(false);}else{stop();}
        
        }
        
        
        }}}
        
      jTextField1.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jButton1ActionPerformed(evt);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tv().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
